### ISSUE TITLE
Doubleslice recently stopped working?

### ISSUE THREAD

**Issue by RulyTafzil** [reyzor1991/foundry-vtt-pf2e-action-support#45]
Doubleslice was working a few days ago. Now gives me the following console error command. This is true even in a new pf2e world with just this module installed.

pf2e-action-support.js:52 Uncaught (in promise) ReferenceError: undefined. hasFeatBySourceId is not defined
[Detected 1 package: pf2e-action-support]
    at doubleSliceWeapons (pf2e-action-support.js:52:1423)
    at Object.doubleSlice (pf2e-action-support.js:52:2151)
    at MacroPF2e.eval (eval at #executeScript (foundry.js:22924:16), <anonymous>:3:21)
    at #executeScript (foundry.js:22928:17)
    at MacroPF2e.execute (foundry.js:22876:35)
    at HotbarPF2e._onClickMacro (foundry.js:78695:20)
    at HTMLLIElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by reyzor1991** [comment]
Fixed
